### ISSUE TITLE
Issues when scanning Steam library

### ISSUE THREAD

**Issue by axewater** [gsabater/backlog.rip#26] opened 2024-04-16 06:49 UTC
I scanned my huge library and it took long (makes sense) but I had no sense of progress. Maybe you can have an indicator (number of games found / processed) while it is scanning.

**Comment by gsabater** [comment] 2024-04-16 06:53
Hey @axewater thanks for reaching out.

I agree with you, the user experience when loading games could be better.
So i can understand a little better. How many games do you have on your library (more or less)? How much time would you say it has taken to process your library?

Thanks for your time

**Comment by axewater** [comment] 2024-04-16 07:30
My library is 900 games. I actually had to reboot in between so it didnt finish (it ran for about 30 minutes) . I'll run it again and time it.

**Comment by axewater** [comment] 2024-04-16 09:37
sure thing I'll hop onto discord.
(i think the issue may be Im on a corporate network)

**Comment by axewater** [comment] 2024-04-16 10:55
ok this is super weird. i started clicking around the site because the index didnt seem to do anything.
it says library 0 games, but then i clikc on it, it tells me again, to have nothing, go scan, but I click on browse games, and there ... i see a ton of my games!

<img width="740" alt="bl2" src="https://github.com/gsabater/backlog.rip/assets/42516026/510ba531-7be7-4b17-b2e3-22e60e3bcc4d">

top right corner still says '0 games'
at the bottom of the screen:

Showing up to 196 of 844 results
No games filtered

**Comment by gsabater** [comment] 2024-04-16 12:54
@axewater 

The discord problem might be mine, i don't know how to make a link to a dm, sorry. You can join the discord channel with https://discord.com/invite/F2sPE5B (no spam intended) 

According to your screens, I think the api didn't get any games , maybe you can open the console (F12) before clicking on scan library and  follow the steps 1, 2 and 3 in this screenshot. Then click the scan button and you will have 4 and 5 with the response 

![image](https://github.com/gsabater/backlog.rip/assets/4948172/9f3f0e2c-2617-42cc-a438-cad95c571dc6)

**Comment by gsabater** [comment] 2024-04-16 13:59
Hello @axewater 
In my end i can solve that the process don't fail if the response is empty. But I think that this might be related to some settings in your profile privacy settings.

Please, review this link 
- https://steamcommunity.com/discussions/forum/1/1696044439573019687/

and then go to your profile privacy settings and tell me what you have
- https://steamcommunity.com/my/edit/settings?snr=2_groupannouncements_detail_

Here is mine for reference
![image](https://github.com/gsabater/backlog.rip/assets/4948172/450342f2-e120-44d6-ae27-d34da3754ddb)

Thanks again

**Comment by gsabater** [comment] 2024-04-17 09:04
@axewater 
The issue is fixed, the problem was due to Steam IDs not being sent correctly by the server due to issues with big ints.

Anyway, i have added the following screens to improve the user experience based on your feedback
- Added a message indicating that the import should be just a few seconds instead of minutes.
![image](https://github.com/gsabater/backlog.rip/assets/4948172/2d0f2a5b-c2dd-4971-a568-1727f0c59963)

- Added a message indicating empty library, and a link to review privacy settings
![image](https://github.com/gsabater/backlog.rip/assets/4948172/27d4244f-11a2-4f68-b67c-3e923f6edff0)

Thanks for your feedback

---

Fixed in release 0.11
Complete changelog in https://steam-backlog.com/changelog

**Closed by gsabater** 2024-04-17 09:04 UTC
Labels: bug, Enhancement
